fieldLayouts:
  67d80a20-36ef-46a8-9f65-74225a5103ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56529378-21ff-44eb-a6c6-899b4ba568f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b8224a02-6b79-4178-9102-06998d5ef05c # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c586f12-9806-4635-96ae-0a60b7a6752c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a00b7830-6ebb-4c7e-b4f4-ceca95ae230d # Post Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45a5dc08-ea02-44d5-8c1a-2484374e6fec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7a9f927-d9d6-4213-939d-c1b5f8ae58fe # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dbac99d-9e09-49ea-be3d-65aabbe77579
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf8a59db-2be1-427e-940b-17eb62806f04 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdb36b1a-e86a-4d0e-a8bb-f66086568968
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a32e0e7-1309-4985-9810-6e0a85425dfb
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: 9ff35442-2678-4c1f-be3b-aff118ca87b3 # Blog
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
