columnSuffix: null
contentColumnType: string
fieldGroup: ce0a5db7-7167-43c5-b421-99ca43588394 # Blog
handle: postCategories
instructions: null
name: 'Post Categories'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:4ca33705-c30d-4ca7-9c1b-a631b7bbe616' # Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
