defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  184b6100-c8c6-4dcc-9195-5af86a62f22a: # sport
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
